name: Bilibili-Task

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 # python installtion
  install-python:
  # should run on linux based operating system
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install python version
      # use the pyenv-action version 7
        uses: gabrielfalcao/pyenv-action@v7
        with:
          default: 3.8.6 # pick 3.8.6 verion 
          command: pip install -U pip  # upgrade pip after installing python
      
      - name: create environment
        run: pyenv local 3.8.6 && python -mvenv .venv386

      - name: Install dependencies
        run: pip install -r requirements.txt --upgrade pip

      - name: run python main
        run: python main.py
      